apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deploy.yaml
- ./remarkdeploy.yaml

images:
- name: lyr8200/blog
  newName: registry.cn-hangzhou.aliyuncs.com/jarhmj/hugo-demo
  newTag: 8189a05
