apiVersion: apps/v1
kind: Deployment
metadata:
  name: remark42
  namespace: blog
  labels:
    app: remark42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remark42
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: blog
      labels:
        app: remark42
    spec:
      containers:
        - name: remark42
          image: umputun/remark42:v1.8.1
          ports:
            - containerPort: 8080
          env:
            - name: REMARK_URL
              value: "https://remark.lyrzyh.com"
            - name: "SITE"
              value: "lyrzyh.com"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: remark42
                  key: SECRET
            - name: TIME_ZONE
              value: "Asia/Shanghai"
          volumeMounts:
            - name: srvvar
              mountPath: /srv/var
          securityContext:
            readOnlyRootFilesystem: false
          resources:
            requests:
              cpu: "100m"
              memory: "25Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: srvvar
          persistentVolumeClaim:
            claimName: remark42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remark42
  namespace: blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: remark42-web
  namespace: blog
spec:
  selector:
    app: remark42
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: remark42-ingress
  namespace: blog
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"    # 开启证书
spec:
  rules:
    - host: "remark.lyrzyh.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: remark42-web
                port:
                  number: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: remark42
  namespace: blog
stringData:
  SECRET: zhuzai2015